In [1]:
name = "ABC"
age = 19
is_student = True
print(name,age,is_student)

ABC 19 True


In [2]:
marks = [85,90,78,92]
print("Marks:",marks)

Marks: [85, 90, 78, 92]


In [3]:
print("First mark:",marks[0])

First mark: 85


In [5]:
student = {"name":"abc","dept": "AI&DS","year":3}
print(student["name"],"is in", student["dept"])


abc is in AI&DS


In [6]:
!pip install numpy

In [7]:
import numpy as np 
arr1 = np.array([1,2,3])
print("1D Array:",arr1)

1D Array: [1 2 3]


In [9]:
arr2= np.array([[1,2,3],[4,5,6]])
print("2D Array:",arr2)

2D Array: [[1 2 3]
 [4 5 6]]


In [10]:
#Numpy Operations

print("Sum:",arr1+10)
print("Square:",arr1 ** 2)
print("Mean:",np.mean(arr1))

Sum: [11 12 13]
Square: [1 4 9]
Mean: 2.0


In [11]:
#Practice Questions
#Create a list of your 5 favorite subjects and print the 2nd and last subject.
subjects = ["Tamil","English","Maths","Science","Social Science"]
print(subjects[1])


English


In [16]:
#Create a dictionary for yourself with keys: "name", "college", "dept", "year". Print only the department.

student = {"name":"Adhira","college":"Ramco Institute of Technology","dept":"AI&DS","Year":3}
print(student["dept"])

AI&DS


In [23]:
#Write a Python function square_numbers(numbers) that takes a list and returns a list of squared numbers.

def square_numbers(numbers):
    squared_list=[]
    for n in numbers:
        squared_list.append(n ** 2)
    return squared_list

nums = [2,4,6,8]
print("Original:",nums)
print("Squared:",square_numbers(nums))

Original: [2, 4, 6, 8]
Squared: [4, 16, 36, 64]


In [30]:
import numpy as np 
n1= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(n1[0:6])
print(n1[-5:])
print(np.mean(n1))
print(np.std(n1))

[1 2 3 4 5 6]
[16 17 18 19 20]
10.5
5.766281297335398


In [33]:
#Create a 2D array (3x3) of random integers between 1–50 using:
#Print the array
#Print the maximum value in the array
#Print the sum of each row
n2=np.random.randint(1, 51, size=(3,3))
print(n2)
print(n2.max())
print(np.sum(n2,axis=1))

[[45 35  9]
 [24 32  2]
 [ 8 10 29]]
45
[89 58 47]


In [34]:
a = np.array([1,2,3])  
b = np.array([4,5,6])  
print("Element-Wise Addition:",a+b)
print("Dot Product:",np.dot(a,b))

Element-Wise Addition: [5 7 9]
Dot Product: 32
